version: '3.8'
services:
  services:
    spark:
      image: bitnami/spark:latest
      restart: unless-stopped
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - spark-data:/bitnami/spark
  spark-worker:
    image: bitnami/spark:latest
    environment:
      environment:
        - SPARK_WORKER_MEMORY=1G
        - SPARK_WORKER_CORES=1
      deploy:
        resources:
          limits:
            memory: 1.2G
            cpus: '1.0'
    depends_on:
      spark:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "8081:8081"
    volumes:
      - spark-worker-data:/bitnami/spark
volumes:
  spark-data:
    driver: local
  spark-worker-data:
    driver: local
